# Generated by Django 5.0.3 on 2024-05-10 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imagefiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageFiles',
            new_name='UserWithImage',
        ),
    ]
