# Generated by Django 5.0.3 on 2024-05-10 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_imagefiles_userwithimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserWithImage',
            new_name='ImageFiles',
        ),
    ]
